'use client'

export const itemTypeMap: Record<string, string> = {
  '0': 'All',
  '1': 'Melee',
  '2': 'Rifle',
  '3': 'Shotgun',
  '4': 'Sniper',
  '5': 'Minigun',
  '6': 'Bazooka',
  '7': 'Grenade',
  '9': 'Set',
  '10': 'Set package',
  '11': 'Hair',
  '12': 'Face',
  '13': 'Top',
  '14': 'Bottom',
  '15': 'Legs',
  '16': 'Hands',
  '17': 'Shoes',
  '19': 'Head',
  '20': 'Waist',
  '21': 'Back',
  '24': 'Convenience',
  '25': 'Diorama',
  '27': '?',
}

export const itemTypes = [
  { value: '0', label: 'All' },
  { value: '1', label: 'Melee' },
  { value: '2', label: 'Rifle' },
  { value: '3', label: 'Shotgun' },
  { value: '4', label: 'Sniper' },
  { value: '5', label: 'Minigun' },
  { value: '6', label: 'Bazooka' },
  { value: '7', label: 'Grenade' },
  { value: '9', label: 'Set' },
  { value: '10', label: 'Set package' },
  { value: '11', label: 'Hair' },
  { value: '12', label: 'Face' },
  { value: '13', label: 'Top' },
  { value: '14', label: 'Bottom' },
  { value: '15', label: 'Legs' },
  { value: '16', label: 'Hands' },
  { value: '17', label: 'Shoes' },
  { value: '19', label: 'Head' },
  { value: '20', label: 'Waist' },
  { value: '21', label: 'Back' },
  { value: '24', label: 'Convenience' },
  { value: '25', label: 'Diorama' },
  { value: '27', label: '?' },
]
